# inventory.compute.gcp.yml
---
plugin: gcp_compute
projects:
  - cc-ws-2122
service_account_file: ~/.gcp-key.json
auth_kind: serviceaccount
hostnames:
  - name
keyed_groups:
  - key: zone
groups:
  # kafka_brokers: inventory_hostname.startswith('kafka')
  zookeeper_servers: inventory_hostname.startswith('zookeeper')
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
